name: 'Codecov'

on:
  push:
    branches:
      - main

jobs:
  codecov:
    name: 'Codecov'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Setup go ${{ env.GO_VERSION }}'
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: 'Test'
        run: 'go test -race -coverprofile=coverage.out -covermode=atomic ./...'
      - name: 'Upload coverage reports to Codecov'
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}